### ISSUE TITLE
README/Plan

### ISSUE THREAD

**Issue by jvoigtlaender** [s6makano/somekindofpuzzle#1]
Verschieben Sie die Informationen aus dem Wiki bitte in eine README.md Datei.

**Comment by s6makano** [comment]
Soll das Wiki bestehen bleiben, gelöscht werden oder mit Informationen anderer Art befüllt werden?

**Comment by jvoigtlaender** [comment]
Ich denke, es kann gelöscht werden. In meiner Wahrnehmung ist das per-Repository-Wiki ein recht selten genutztes GitHub-Feature. Ich wäre nie auf den Gedanken gekommen, da nachzuschauen, wenn Sie nicht per Email darauf hingewiesen hätten.
