### ISSUE TITLE
Build-Anweisung, .cabal-File

### ISSUE THREAD

**Issue by jvoigtlaender** [s6makano/somekindofpuzzle#4]
Ich muss wissen, wie sich das Projekt bauen lässt, welche Abhängigkeiten in welchen Versionen benötigt werden.

https://wiki.haskell.org/How_to_write_a_Haskell_program

**Comment by s6makano** [comment]
Alles getan wie im Link vorgeschlagen, verschiedentliches probiert, aber die Bilder werden weder bei relativen noch bei absoluten Pfaden erkannt. Daher auf lokal kompilierbar zurückgesetzt.

**Comment by x432ph** [comment]
Jetzt sogar mit funktionierender .cabal-Installation!!!!!
