### ISSUE TITLE
Organisation des Repositories

### ISSUE THREAD

**Issue by jvoigtlaender** [s6makano/somekindofpuzzle#5]
Üblich und besser wäre, nicht alle möglichen Dinge im Wurzelverzeichnis zu mischen. Stattdessen zum Beispiel die `.hs` Dateien in ein Unterverzeichnis `src`, die `.png` Dateien in ein Unterverzeichnis `assets`. Im `.cabal`-File gibt es Möglichkeiten, diese Struktur zu deklarieren, also was Programm- und was Datenverzeichnisse sind.

**Comment by s6makano** [comment]
Geordnet, aber trotzdem gescheitert, siehe anderer Issue.
